	.code
j_dt:
j_pconst:

j_data2:
j_title:
j_name:
j_proc:
j_endp:
j_end:
j_label:
j_string:
j_array:
j_local:
j_extrn:
j_byte:
j_word:
j_dword:
j_qword:
j_tword:
j_signed:
j_char:
j_short:
j_near:
j_far:
j_ptr:
j_offset:
j_sizeof:
j_low:
j_high: stc
	ret
j_else:
j_ifb:
j_ifnb:
j_ifdef:
j_ifndef:
j_case:

j_endm:
j_rept:
j_irp:
j_irpc:
j_exitm:
j_while:
j_wend:
j_repeat:
j_until:
j_purge:

j_incbin:
;	 call update_label
;	 call get_include
;	 mov dx,buffer16
;	 call open_file
	;(WHAMM!)
j_incobj:
j_append:
j_plib:

j_alpha:
j_seq:

j_uses:
j_typedef:
j_equ:
j_startup:

j_option:
J_DOSSEG:
J_SUBSTR:
J_CATSTR:
J_SIZESTR:
J_INSTR:
J_PTYPE:
j_exit: stc
	ret


